sudo: false
language: node_js
node_js:
  - "8"
  - "9"

matrix:
  fast_finish: true
  include:
    - node_js: "node"

install:
  - npm install -g codecov istanbul

script:
  - npm run lint
  - npm run test
  - npm run coverage
