name: shokku
version: 0.1.0
appVersion: 0.1.0
description: Shokku - An open source scalable blockchain infrastructure for Ubiq, Ethereum and IPFS
keywords:
- ubiq
- ethereum
- geth
- gubiq
- jsonrpc
- application
home: https://shokku.com/
sources:
- https://github.com/ubiq/shokku
engine: gotpl
